with CTE as (

Select STARTED_AT,

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('SAT', 'SUN')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,


CASE 
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
THEN 'WINTER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,41,52)
THEN 'SPRING'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,2,8)
THEN 'SUMMER'
ELSE 'AUTUM'
END AS STATION_OF_YEAR

from 
{{ source('DEMO', 'BIKE1') }}

)

Select * from CTE
